* <<<301>>> DISCRETE MATHMATICS
:properties:
:author: Dr. R. Sundareswaran and Dr. N. Padmapriya
:date:
:end:

#+begin_comment
- 1. Almost the same as AU
- 2. For changes, see the individual units.
- 3. Not Applicable
- 4. Five Course outcomes specified and aligned with units
- 5. Not Applicable
#+end_comment

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 2 | 0 | 4 |

** COURSE OBJECTIVES
   - To study the concepts of classical logic, normal forms and its
     applications.
   - To solve problems using different counting techniques.
   - To learn the basic concepts in graph theory and prove simple
     properties.
   - To study the algebraic structures.
   - To study the concept of Boolean algebra.

{{{unit}}}
|UNIT I | LOGIC AND PROOFS  | 13 |
Propositional Logic -- Propositional equivalences -- Predicates and
quantifiers -- Nested quantifiers -- Rules of inference --
Introduction to proofs -- Proof methods and strategy -- Normal forms
-- Applications to switching circuits.
#+begin_comment
Added: Normal forms -- Applications to switching circuits.
#+end_comment

{{{unit}}}
|UNIT II | COMBINATORICS | 11 |
Mathematical induction -- Strong induction -- The pigeonhole principle
-- Recurrence relations -- Partition of integers -- Solving linear
recurrence relations using generating functions -- Inclusion and
Exclusion Principle and its applications.

{{{unit}}}
|UNIT III | GRAPHS | 10 |
Graphs -- Graph terminology and special types of graphs -- Subgraphs
-- Matrix representation of graphs and graph isomorphism --
Connectivity -- Eulerian and Hamilton graphs.

{{{unit}}}
|UNIT IV | ALGEBRAIC STRUCTURES | 13 |
Algebraic systems -- Semi groups and monoids -- Groups -- Subgroups
Homomorphisms -- Normal subgroup and coset -- Lagrange's theorem --
Definitions and examples of Rings and Fields.

{{{unit}}}
|UNIT V | LATTICES AND BOOLEAN ALGEBRA | 13 |
Partial ordering -- Posets -- Lattices as Posets -- Properties of
lattices -- Lattices as algebraic systems -- Sublattices -- Direct
product and Homomorphism; Boolean algebra -- Stone's representation
Theorem.
#+begin_comment
Added: Stone's representation Theorem. 
#+end_comment

\hfill *Total Periods: 60*

** COURSE OUTCOMES
After the completion of this course, students will be able to:
- Write simple proofs using Propositional and First-Order Logics
- Solve problems using different counting techniques
- Prove simple graph properties.
- Explain basic concepts in group theory such as semigroups, monoids
  and groups.
- Solve problems in partial ordering relations, equivalence relations
  and lattices.

** TEXT BOOKS
1. Kenneth H Rosen, ``Discrete Mathematics and its Applications'', 7th
   Edition, Special Indian edition, Tata McGraw Hill, New Delhi, 2017.
2. Tremblay J P and Manohar R, ``Discrete Mathematical Structures with
   Applications to Computer Science'', 30th Reprint, Tata McGraw Hill,
   New Delhi, 2011.

** REFERENCES
1. Ralph P Grimaldi, ``Discrete and Combinatorial Mathematics: An
   Applied Introduction'', 4th Edition, Pearson Education Asia, 2007.
2. Eric Lehman, F Tom Leighton, Albert R Meyer, ``Mathematics for
   Computer Science'', Samurai Media Limited, 2017.
3. Thomas Koshy, ``Discrete Mathematics with Applications'', Elsevier
   Publications, 2006.
4. Seymour Lipschutz, Mark Lipson,``Discrete Mathematics'',
   Schaum's Outlines, 3rd Edition, Tata McGraw Hill, 2010.
5. C L Liu, D P Mohapatra, ``Elements of Discrete Mathematics'', 4th
   Edition, McGraw Higher Education, 2017.
6. John M Harris, Jeffry L Hirst, Michael J Mossinghoff,
   ``Combinatorics and Graph Theory'', Springer verlag New
   York, 2008.
