* <<<401>>> PROBABILITY AND STATISTICAL METHODS
:properties:
:author: Dr. G. Kalpana and Dr. N. Padmapriya
:date: 
:end:

#+startup: showall

{{{credits}}}
| L | T | P | C |
| 3 | 2 | 0 | 4 |

** COURSE OBJECTIVES
- To identify the standard distributions and apply them in solving
  problems.
- To solve problems in joint probabilities and to find correlation
  between them.
- To perform hypothesis testing using normal, t, F, chi square
  distribution
- To evaluate the tests of significance in analysis of variance.
- To calculate the various statistical quality control measurements.

{{{unit}}}
| UNIT I | RANDOM VARIABLES | 12 |
Random variables -- Discrete and continuous random variables --
Moments -- Moment generating functions -- Binomial, Poisson,
Geometric, Uniform, Exponential, Gamma, Normal distributions --
Functions of a random variable.

{{{unit}}}
| UNIT II | TWO-DIMENSIONAL RANDOM VARIABLES | 12 |
Joint distributions -- Marginal and conditional distributions --
Covariance -- Correlation and linear regression -- Transformation of
random variables -- Central limit theorem (for independent and
identically distributed random variables).

{{{unit}}}
| UNIT III | TESTS OF SIGNIFICANCE | 12 |
Sampling distributions -- Small and large sample test -- Test based on
Normal and t distribution (Single and difference of mean)-- \chi^2 --
Test for goodness of fit, Independence of attributes- F test for
variance.

{{{unit}}}
| UNIT IV | DESIGN OF EXPERIMENTS | 12 |
Completely randomized design -- Randomized block design -- Latin
square design -- Factorial design.

{{{unit}}}
| UNIT V | 	STATISTICAL QUALITY CONTROL | 12 |
Control charts for measurements (X and R charts) -- Control charts for
attributes (p, c and npcharts) -- Tolerance limits -- Acceptance
sampling.

\hfill *Total Periods: 60*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Identify standard distributions and apply them
- Solve problems in two dimension random variables and find the
  correlation between them
- Identify and apply the suitable testing of hypothesis under normal,
  t, F and chi square distribution
- Solve problems in analysis of variance
- Analyze quality control by applying control chart methods.
      
** TEXT BOOKS
1. Milton J S and Arnold J C, ``Introduction to Probability and
   Statistics'', 4th Edition, 3rd Reprint, Tata McGrawHill, 2014.
2. Johnson R A and Gupta C B, ``Miller and Freund's Probability and
   Statistics for Engineers'', 9th Edition, Pearson Education, 2016.

** REFERENCES
1. Devore J L, ``Probability and Statistics for Engineering and the
   Sciences'', 8th Edition, ThomsonBrooks/Cole, International Student
   Edition, 2012.
2. Walpole R E, Myers R H, Myers S L, Ye K, ``Probability and
   Statistics for Engineers and Scientists'', 9th Edition, Pearson
   Education, Asia, 2012.
3. Ross S M, ``Introduction to Probability and Statistics for
   Engineers and Scientists'', 5th Edition, Elsevier, New Delhi, 2014.
4. Spiegel M R, Schiller J, Srinivasan R A, ``Schaum’s
   Outline of Theory and Problems of Probability and Statistics'',
   3rd Edition, Tata McGraw Hill, New Delhi, 2004.
5. Gupta S C, Kapoor V K, ``Fundamentals of Mathematical Statistics'',
   12th Edition, Sultan and Chand Company, New Delhi, 2020.
