* <<<PE307>>> DATA SECURITY AND PRIVACY
:properties:
:author: Dr. V. Balasubramanian and Dr. J. Bhuvana
:date: 10-03-2021
:end:

#+startup: showall
#+begin_comment
Topic:
1. Introduction to web security alone is discussed in unit 3.
2. Due to limited hours,  indepth topics on Web security cannot be included.
3. OWASP deals with web application security.

Regarding BoS Comments:

1. As per suggestions, Unit III is revised.

2. Book suggested by BoS handles Cryptography and it deviates from the
course content.
#+end_comment

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To study about the essentials of computer security
- To acquire knowledge on TCP/IP security, firewalls, IPSec, Virtual
  Private Networks, and intrusion detection systems
- To understand how various security mechanisms work, and correlate
  these security mechanisms with security principles
- To learn the security aspects of data center
- To learn the security protocols and technologies with respect to
  infrastructure.

{{{unit}}}
         
| UNIT I | OVERVIEW OF SECURITY AND  ENCRYPTION TECHNIQUES | 11 |

Overview: Computer Security Concepts -- Threats, Attacks, and Assets -- Security Functional Requirements -- Fundamental Security Design Principles -- Attack Surfaces and Attack Trees -- Computer Security Strategy; Symmetric Encryption and Message Confidentiality: Symmetric Encryption Principles --  Data Encryption Standard --  Advanced Encryption Standard --  Stream Ciphers and RC4 --  Cipher Block Modes of Operation --  Key Distribution; Public-Key Cryptography and Message Authentication: Secure Hash Functions -- HMAC --  RSA -- Diffie-Hellman and Other Asymmetric Algorithms;
 
 {{{unit}}}
      
| UNIT II | ACCESS CONTROL  AND INTERNET AUTHENTICATION APPLICATIONS            | 9 |

User Authentication: Electronic User Authentication Principles -- Password-Based Authentication -- Token-Based Authentication -- Biometric Authentication -- Remote User Authentication;
Internet Authentication Applications: Kerberos --  X.509 -- Public-Key Infrastructure

{{{unit}}}
      
| UNIT III | SOFTWARE SECURITY AND OPERATING SYSTEM SECURITY            | 9 |

Software Security: Software Security Issues -- Handling Program Input --  Writing Safe Program Code -- Interacting with the Operating System and Other Programs -- Handling Program Output;
Operating System Security : Introduction to Operating System Security -- System Security Planning -- Operating Systems Hardening -- Application Security -- Security Maintenance -- Linux/Unix Security -- Windows Security -- Virtualization Security;
Cloud and IoT security:  Cloud Computing -- Cloud Security Concepts -- Cloud Security Approaches -- The Internet of Things --  IoT Security

{{{unit}}}
      
| UNIT IV | ACCESS CONTROL MATRIX AND  SECURITY POLICIES              | 8 |

 Access Control Matrix: Protection State-- Access Control Matrix Model -- Protection State Transitions -- Copying, Owning, and the Attenuation of Privilege;
Security Policies: The Nature of Security Policies -- Types of Security Policies -- The Role of Trust -- Types of Access Control -- Policy Languages -- Example: Academic Computer Security Policy -- Security and Precision 

{{{unit}}}
      
| UNIT V |  SECURITY POLICIES             | 8 |
The Nature of Security Policies -- Types of Security Policies -- The Role of Trust; 
Confidentiality policy:The Bell-LaPadula Model; Integrity policy: Clark-Wilson Integrity Model; Availability policy: Denial of Service Models; Hybrid policy:  Chinese Wall Model


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Understand the essentials of computer security (K2) 
- Understand various applications of network security (K2) 
- Understand the essentials of security practices and system security (K2)
- Explain the security aspects in designing a datacenter (K2) 
- Design the security protocols for the infrastructure (K3)

** TEXT BOOKS

1. William Stallings, Lawrie Brown, ``Computer Security  Principles and Practice'', Fourth Edition, Pearson, 2019 (Unit I--III).
2. Matt Bishop, ``Computer Security: Art and Science'', Second edition, Addison Wesley, 2019 (Unit IV, V).


** REFERENCES
1. Salomon, David , ``Data Privacy and Security'', Springer
2. Dorothy Elizabeth Rob, ling Denning , ``Cryptography and data Security'',   ADDISON-WESLEY PUBLISHING COMPANY, 2003 
3. Houbing Song , Glenn A. Fink , Sabina Jeschke ,  ``Security and Privacy in Cyber-Physical Systems: Foundations, Principles, and Applications'',  Wiley-IEEE Press, November 2017 
4. Charlie Kaufman, Radia Perlman and Mike Speciner , ``Network Security: Private Communication in a Public World'', Second  Edition, Pearson Education, 2017.
5. Wenliang Du, ``Computer Security: A Hands-on Approach'', CreateSpace Independent Publishing Platform, First Edition, 2017.
6. William Stallings, ``Network Security Essentials: Applications and    Standards'', Sixth Edition, Pearson, 2017.
7. Mauricio Arregoces, Maurizio Portolani, ``Data Center    Fundamentals'', Cisco Press, 2003.

    
 




