* <<<PE106>>> ETHICAL HACKING
:properties:
:author: R Kanchana
:date: 
:end:
#+startup: showall
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   2 |   3 |    2 |    0 |    3 |    2 |    3 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   2 |   3 |    2 |    0 |    3 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   2 |   3 |    2 |    0 |    3 |    2 |    3 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   2 |   3 |    2 |    0 |    3 |    2 |    3 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   2 |   3 |    2 |    0 |    3 |    2 |    3 |    1 |
| Score          |    |  15 |  10 |  10 |  10 |   5 |   0 |   0 |  10 |  15 |   10 |    0 |   15 |   10 |   15 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   1 |   0 |   0 |   2 |   3 |    2 |    0 |    3 |    2 |    3 |    1 |

{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES

- To learn about the importance of information security
- To learn different scanning and enumeration methodologies and tools
- To understand various hacking techniques and attacks
- To be exposed to programming languages for security professionals
- To get familiarized with the different phases in penetration testing

{{{unit}}}
| UNIT I | FUNDAMENTALS OF HACKING | 9 |
Introduction to Hacking – Importance of Security – Elements of Security – Phases of an Attack – Types of Hacker
Attacks – Hacktivism – Vulnerability Research – Introduction to Foot printing – Information Gathering Methodology – Foot
printing Tools – WHOIS Tools – DNS Information Tools – Locating the Network Range – Meta Search Engines.

{{{unit}}}
|UNIT II | SCANNING AND ENUMERATION | 9 |
Introduction to Scanning – Objectives – Scanning Methodology – Tools – Introduction to Enumeration – Enumeration
Techniques – Enumeration Procedure – Tools.

{{{unit}}}
|UNIT III | SYSTEM HACKING  | 9 |
Introduction – Cracking Passwords – Password Cracking Websites – Password Guessing – Password Cracking Tools –
Password Cracking Counter measures – Escalating Privileges – Executing Applications – Key loggers and Spyware.

{{{unit}}}
|UNIT IV | PROGRAMMING FOR SECURITY PROFESSIONALS | 9 |
Programming Fundamentals – C language – HTML – Perl – Windows OS Vulnerabilities – Tools for Identifying
Vulnerabilities – Countermeasures – Linux OS Vulnerabilities – Tools for Identifying Vulnerabilities – Countermeasures.


{{{unit}}}
|UNIT V | PENETRATION TESTING       | 9 |
Introduction – Security Assessments – Types of Penetration testing – Phases of Penetration Testing – Tools –Test Tools
– Penetration Testing Tools.
 
\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Defend hacking attacks and protect data assets.
- Defend a computer against a variety of security attacks using various tools.
- Practice and use safe techniques on the World Wide Web.
- Write the programming for security professionals.
- Know the different testing tools.

** TEXT BOOKS
1. Patrick Engebretson, “The Basics of Hacking and Penetration Testing – Ethical Hacking and Penetration Testing
Made Easy”, Syngress Media, Second Revised Edition, 2013.
2. Michael T. Simpson, Kent Backman and James E. Corley, “Hands-On Ethical Hacking and Network Defense”,
Cengage Learning, Third Edition 2017

** REFERENCES
3. Jon Erickson, Hacking: “The Art of Exploitation”, No Starch Press, Second Edition, 2010.
4. Ec-Council, “Ethical Hacking and Countermeasures”, Delmar Cengage Learning, 2017

