* <<<PE207>>> WIRELESS AD HOC AND SENSOR NETWORKS 
:properties:
:author: Dr. S. V. Jansi Rani and Dr. V. S. Felix Enigo
:date: 10-03-2021
:end:

#+begin_comment
- 1. Removed unit 5 (security)
- 2. included simulation
- 3. included topology control
- 4. 
- 5. 
#+end_comment

#+startup: showall

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K2 |   2 |   2 |   1 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| CO2            | K2 |   2 |   2 |   1 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| CO3            | K2 |   2 |   2 |   1 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| CO4            | K3 |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |
| CO5            | K2 |   2 |   2 |   1 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    1 |    2 |    1 |
| Score          |    |  11 |  10 |   6 |   0 |   5 |   0 |   0 |   5 |   5 |    5 |    0 |    5 |    6 |   11 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   0 |   1 |   0 |   0 |   1 |   1 |    1 |    0 |    1 |    2 |    3 |    1 |


{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

** COURSE OBJECTIVES
- To understand the working of MAC Protocols and routing in  ad hoc networks
- To learn about Transport layer protocols and QOS in ad hoc networks
- To understand the working of topology control and routing protocols in WSN
- To understand the protocols for MAC and localisation in WSN
- To learn about the data centric and content based networking, transport layer protocols and QOS in WSN
- To implement various protocols of wireless networks using simulator

{{{unit}}}
|UNIT I | MAC AND ROUTING IN AD HOC NETWORKS | 9 |
Introduction -- Issues and challenges in ad hoc networks -- MAC Layer
Protocols for wireless ad hoc networks -- Contention-Based MAC
protocols -- MAC Protocols using Directional Antennas --
Multiple-Channel MAC Protocols -- Power-Aware MAC Protocols -- Routing
in Adhoc Networks -- Design Issues -- Proactive, Reactive and Hybrid
Routing Protocols.

{{{unit}}}
|UNIT II | TRANSPORT AND QOS IN AD HOC NETWORKS | 9 |

TCP's challenges and Design Issues in Ad Hoc Networks -- Transport protocols for ad hoc networks -- Issues and Challenges in providing
QoS -- MAC Layer QoS solutions -- Network Layer QoS solutions -- QoS Model - Simiulation of TCP protocol in Ad hoc networks. 

{{{unit}}}
|UNIT III | WSN:  Protocols for MAC and Localization  | 9 |

Fundamentals of MAC Protocols;  Types of MAC Protocols -- Low duty cycle protocols -- Contention-based protocols -- Schedule-based protocols ; 
IEEE 802.15.4 MAC protocol  - Simulation of MAC Protocol;  

Localization and Positioning:  Properties -- Approaches -- Mathematical basis;  
Single Hop Localization -- Positioning in multichip environments  -- Impact of anchor placement.


{{{unit}}}
|UNIT IV | WSN:  Topology Control  and Routing Protocols  | 9 |

Topology Control: Controllingtopology in flat networks --Hierarchical networks by domination sets and clustering -- Combine hierarchical topologies and power control.

Routing Protocols: Unicast -- Broadcast -- Multicast -- Geographical routing -- Mobile nodes -Simulation of routing protocol in WSN.

{{{unit}}}
|UNIT V | WSN: Data centric and Content based networking, Transport layer and QOS | 9 |

Data-Centric and Contention-Based Networking:  Data-centric routing -- Data aggregation -- Data-centric storage.

Transport Layer and Quality of Service: Coverage and deployment -- Reliaable data transport -- Single packet delivery -- Block delivery 
-- Congestion Control and rate control -- Operating systems for wireless sensor networks -- Examples.

\hfill *Total Periods: 45*

** COURSE OUTCOMES
- Explain the working of MAC Protocols and routing in  ad hoc networks (K2)
- Select the various Transport layer protocols considering the QOS in ad hoc networks(K3)
- Make use of the working of topology control and routing protocols in WSN (K3)
- Choose the MAC protocol based on the type of localisation in WSN (K3)
- Choose appropriate networking approach and use transport layer protocol considering the QOS in WSN (K3)
- Apply the various protocols of wireless networks using simulator (K3)

** TEXT BOOKS 
1. C Siva Ram Murthy, B S Manoj, ``Ad Hoc Wireless Networks –
   Architectures and Protocols'', Pearson Education, 2006.
2. Holger Karl, Andreas Willing,``Protocols and Architectures for
   Wireless Sensor Networks'', John Wiley & Sons, 2005.

** REFERENCES
1. Subir Kumar Sarkar, T G Basavaraju, C Puttamadappa, ``Ad Hoc Mobile
   Wireless Networks'', Auerbach Publications, 2008.
2. Carlos De Morais Cordeiro, Dharma Prakash Agrawal, ``Ad Hoc and
   Sensor Networks: Theory and Applications (2nd Edition)'', World
   Scientific Publishing, 2011.
3. Waltenegus Dargie, Christian Poellabauer, ``Fundamentals of
   Wireless Sensor Networks Theory and Practice'', John Wiley and
   Sons, 2010.
4. Xiang-Yang Li , ``Wireless Ad Hoc and Sensor Networks: Theory and
   Applications'', Cambridge university Press, 2008.
5. http://vlabs.iitkgp.ac.in/ant/8/
6. http://vlabs.iitkgp.ac.in/ant/7/theory/
