* <<<PE507>>> MOBILE AND WIRELESS SECURITY
:properties:
:author: Dr. A. Beulah and Dr. J. Bhuvana
:end:

#+startup: showall
#+begin_comment
Yet to do co-po mapping, c-objs, c-outcomes, ref
#+end_comment

** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K2 |   2 |   2 |   1 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    1 |    2 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| Score          |    |  14 |  10 |   9 |   9 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    5 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |



{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

#+begin_comment

#+end_comment

** COURSE OBJECTIVES
- Understand 
- Be familiar 
- Be exposed 
- Learn 
- 

{{{unit}}}
| UNIT I | VULNERABILITIES OF WIRED AND WIRELESS NETWORKS | 9 |

Introduction: Security in the digital age -- Threats and risks to telecommunications systems -- From wireline vulnerabilities to vulnerabilities in wireless communications.
Fundamental Security Mechanisms : Basics on security --  Authentication --Access control.

| UNIT II | WIRELESS SECURITY | 12 |
#+begin_comment
Bluetooth, Wi-Fi and Ad Hoc Networks Security 
#+end_comment

Bluetooth technical specification -- Bluetooth security.
Wi-Fi Security: Attacks on wireless networks -- Security in the IEEE 802.11-- Security in 802.1x -- Authentication in wireless networks -- Layer 3 security mechanisms.
Security in Ad Hoc Networks :  Attacks to routing protocols -- Security mechanisms.

| UNIT III | SECURITY IN MOBILE TELECOMMUNICATION NETWORKS | 8 |

Security in the GSM: Security mechanisms in GSM  -- Security flaws in GSM radio access -- Security flaws in GSM signaling; GPRS security: GPRS architecture -- GPRS security mechanisms -- 3G security: UMTS infrastructure --  UMTS security ; 4G Security.

| UNIT IV | MOBILE HARDWARE SECURITY | 8 |
Platform Boot Integrity -- Secure Storage -- Isolated Execution -- Device Identification -- Device Authentication -- Hardware Security Architectures -- TEE Standards.

| UNIT V | MOBILE PLATFORM SECURITY | 8 |

Android Based Security: Attacks and Threats -- Security extensions for Android.

iOS Based security: Limits of Apple's application vetting process -- iOS security extensions.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Identify (K3)
- Explain  (K3)
- Analyze  (K3)
- Explain  (K2)
-  (K3).

** TEXT BOOKS
1. Hakima Chaouchi, Maryline Laurent-Maknavicius, ``Wireless and Mobile Network Security'',   Wiley-ISTE, June 2009 (Unit I--III).
2. N. Asokan, Lucas Vincenzo Davi, Alexandra Dmitrienko, Stephan Heuser, Kari Kostiainen, Elena Reshetova, Ahmad-Reza Sadeghi,  ``Mobile Platform Security'', Synthesis Lectures on Information Security, Privacy, and Trust, Morgan &Claypool Publishers, 2013 (Unit IV, V).

** REFERENCES




