* <<<PE506>>> MOBILE COMPUTING
:properties:
:author: Dr. V. S. Felix Enigo and Ms. A. Beulah
:date: 13/03/2021
:end:

#+startup: showall


** CO PO MAPPING :noexport:
#+NAME: co-po-mapping
|                |    | PO1 | PO2 | PO3 | PO4 | PO5 | PO6 | PO7 | PO8 | PO9 | PO10 | PO11 | PO12 | PSO1 | PSO2 | PSO3 |
|                |    |  K3 |  K4 |  K5 |  K5 |  K6 |   - |   - |   - |   - |    - |    - |    - |   K5 |   K3 |   K6 |
| CO1            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO2            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO3            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| CO4            | K2 |   2 |   2 |   1 |   1 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    1 |    2 |    1 |
| CO5            | K3 |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |
| Score          |    |  14 |  10 |   9 |   9 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    5 |    9 |   14 |    5 |
| Course Mapping |    |   3 |   2 |   2 |   2 |   0 |   0 |   0 |   0 |   0 |    0 |    0 |    1 |    2 |    3 |    1 |



{{{credits}}}
| L | T | P | C |
| 3 | 0 | 0 | 3 |

#+begin_comment
- 1. Five Course outcomes specified and aligned with units
- 2. CO6 added to cover soft POs
- 3. NA
- 4. 2 text and 5 Reference books 
- 5. LTPC checked
- 6. Hours distributed based on number and depth of the topics
- 7. KL and Co matches the depth of the topics
- 8. 4 COs in K3/k4
#+end_comment

** COURSE OBJECTIVES
The student should be made to:
- Understand the basic concepts of mobile computing
- Know the functionalities of layers in protocol stack
- Learn the basics of mobile telecommunication system
- Gain knowledge about different mobile platforms and application development environments
- Develop applications using Andriod Platform

{{{unit}}}
|UNIT I | INTRODUCTION | 9 |
Introduction to Mobile Computing; Media Access Control (MAC):
Motivation for a specialized MAC-- SDMA -- FDMA -- TDMA -- CDMA --
Comparison of S/T/F/CDMA; Wireless LAN: Infrastructure based and adhoc
networks -- IEEE 802.11 -- Bluetooth.

{{{unit}}}
|UNIT II | NETWORK AND TRANSPORT LAYER | 9 |
Mobile IP: Goals, assumptions and requirements -- Entities and
terminology -- IP packet delivery -- Agent discovery -- Registration
--Tunneling and encapsulation -- Optimizations; DHCP; AdHoc: Routing
-- Proactive routing protocol-DSDV -- Reactive routing protocol - DSR, 
AODV -- Hybrid routing –ZRP; Traditional TCP – Classical TCP improvements.


{{{unit}}}
|UNIT III | MOBILE TELECOMMUNICATION SYSTEMS | 9 |
Introduction; GSM Overview; 3GPP; UMTS  and  IMT-2000: Architecture --  User  Equipment --  RNS --  UTRAN -- Node B -- RNC Functions -- IP Multimedia Subsystem; 4G Cellular Network: LTE Network Architecture -- EPS Interfaces -- EPS Protocols and Planes -- LTE Protocol Strack -- SDU and PDU -- RRC -- PDCP -- RLC -- MAC -- PHY.

{{{unit}}}
|UNIT IV | MOBILE PLATFORMS | 8 |
iOS: iOS Architecture Layers -- iOS Simulator; Android: Introdution to Android -- Android's Development Environment.

{{{unit}}}
|UNIT V | EXERCISING THE ANDROID SDK| 10 |
User Interfaces -- Intents and services -- Storing and Retrieving data -- Notifications and alarms -- Location --  Putting Android to work in a field service application.


\hfill *Total Periods: 45*

** COURSE OUTCOMES
- Explain the functionalities of MAC protocols in wireless networks (K2)
- Choose appropriate algorithms for routing and transporting data for a given scenario (K3)
- Demonstrate the concepts of 3G and 4G Cellular Networks (K2)
- Make of use various mobile development environments (K3)
- Develop Andriod applications for the given requirements (K3)
- Analyze the given requirements and build Android applications (K4)

** TEXT BOOKS
1. Jochen H Schller, ``Mobile Communications'', Pearson Education, New
   Delhi, 2nd Edition, 2007 (Unit I--III).
2. Ableson, W.F., Sen, R. and King, C., 2011. ``Android in Action Second Edition'', Manning Publications Co.(Unit IV,V)

** REFERENCES
1. ElNashar, A., El-Saidny, M.A. and Sherif, M., 2014. ``Design, deployment and performance of 4G-LTE networks: A practical approach'', John Wiley & Sons.(4G)
2. Helal, Sumi, Raja Bose, and Wendong Li. ``Mobile platforms and development environments'', Synthesis Lectures on Mobile and Pervasive Computing, 2012.(iOS)
3. Helal, Abdelsalam A., et al. ``Any time, anywhere computing: Mobile computing concepts and technology'', Vol. 522. Springer Science & Business Media, 1999.
4. Dharma Prakash Agarval, Qing and An Zeng, ``Introduction to Wireless and Mobile systems'', Thomson Asia Pvt Ltd, 2005.	
5. C.K.Toh, ``AdHoc Mobile Wireless Networks'', First Edition, Pearson Education, 2002.





