* <<<PE605>>> REINFORCEMENT LEARNING
:properties:
:author: Ms. M. Saritha and Ms. S. Rajalakshmi
:date: 09-03-2021
:end:

#+begin_comment
- 1. 
#+end_comment

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** COURSE OBJECTIVES
- To understand the basics of probability theory and reinforcement learning
- To explore various methods used in reinforcement learning
- To apply reinforcement learning techniques for various case studies


{{{unit}}}
| UNIT I | BASICS OF PROBABILITY THEORY | 9 |


{{{unit}}}
| UNIT II | INTRODUCTION TO REINFORCEMENT LEARNING | 7 |
Reinforcement Learning -- Examples -- Elements of Reinforcement Learning -- Limitations and Scope -- An Extended Example: Tic-Tac-Toe.


{{{unit}}}
| UNIT III |  | TABULAR SOLUTION METHODS | 11 |
Multi-armed Bandits: A k-armed Bandit problem -- Action-value methods -- Incremental implementation -- Tracking a nonstationary problem -- Optimistic initial values -- Upper-confidence-bound action selection; Finite Markov Decision Processes; Dynamic Programming; Monte Carlo Methods; Temporal-Difference Learning.

{{{unit}}}
| UNIT IV |  | APPROXIMATE SOLUTION METHODS | 10 |
On-policy Prediction with Approximation; On-policy Control with Approximation; Off-policy Methods with Approximation; Eligibility Traces; Policy Gradient Methods. 

#+begin_comment

#+end_comment

{{{unit}}}
| UNIT V | APPLICATIONS AND CASE STUDIES | 8 |
TD-Gammon; Samuel’s Checkers Player; Watson’s Daily-Double Wagering; Optimizing Memory Control; Human-level Video Game Play; Personalized Web Services.

#+begin_comment
- 1. 
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- To understand the basics of probability theory (K2)
- To outline the elements of reinforcement learning (K2)
- To illustrate tabular solution methods for various problems (K2)
- To explain approximate solution methods for different problems (K2)
- Apply reinforcement learning techniques for various case studies (K3).

** TEXT BOOKS
1. Richard S. Sutton & Andrew G. Barto, ``Reinforcement Learning: An Introduction'', The MIT Press, 2nd Edition, 2018.
2. 

** REFERENCES
1. 
2. 
