* <<<PE605>>> REINFORCEMENT LEARNING
:properties:
:author: Ms. M. Saritha and Ms. S. Rajalakshmi
:date: 09-03-2021
:end:

#+begin_comment
- 1. 
#+end_comment

#+startup: showall

{{{credits}}}
|L|T|P|C|
|3|0|0|3|

** COURSE OBJECTIVES
- To understand the basics of probability theory and reinforcement learning
- To explore various methods used in reinforcement learning
- To apply reinforcement learning techniques for various case studies


{{{unit}}}
| UNIT I | BASICS OF PROBABILITY THEORY | 9 |


#+begin_comment


#+end_comment


{{{unit}}}
| UNIT II | INTRODUCTION TO REINFORCEMENT LEARNING | 6 |
Reinforcement Learning -- Examples -- Elements of Reinforcement Learning -- Limitations and Scope -- An Extended Example: Tic-Tac-Toe.


{{{unit}}}
| UNIT III |  | TABULAR SOLUTION METHODS | 10 |
Multi-armed Bandits: A k-armed Bandit Problem -- Action-value Methods -- Incremental Implementation -- Tracking a Nonstationary Problem -- Optimistic Initial Values -- Upper-Confidence-Bound Action Selection; Finite Markov Decision Processes: The Agent–Environment Interface -- Goals and Rewards -- Returns and Episodes -- 

{{{unit}}}
| UNIT IV |  | APPROXIMATE SOLUTION METHODS |


#+begin_comment

#+end_comment

{{{unit}}}
|UNIT V|APPLICATIONS AND CASE STUDIES|9|
XML Retrieval -- Multimedia IR -- Parallel and Distributed IR --
Digital Libraries -- Social Media Retrieval -- Content-based Image
Retrieval -- Online Public Access Catalogs (OPACs).

#+begin_comment
- 1. 
#+end_comment

\hfill *Total Periods: 45*

** COURSE OUTCOMES
After the completion of this course, students will be able to: 
- Describe various IR modeling techniques (K3)
- Identify and design the various components of an Information
  Retrieval system (K3)
- Apply machine learning techniques to text classification and
  clustering for efficient Information Retrieval (K3)
- Describe various IR applications (K2)
- Apply IR evaluation metrics to measure the performance of IR
  systems (K3).

** TEXT BOOKS
1. Richard S. Sutton & Andrew G. Barto, ``Reinforcement Learning: An Introduction'', The MIT Press, 2nd Edition, 2018.
2. 

** REFERENCES
1. 
2. 
